[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"
PNPM_VERSION = "8"

[build]
# for demo or preview
command = "pnpm install --ignore-scripts --frozen-lock && pnpm prepare && pnpm build && pnpm docs:build"
publish = "dist"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

